pulsar:
  broker_url: pulsar://pulsar-broker.pulsar.svc.cluster.local:6650
  http_url: http://pulsar-broker.pulsar.svc.cluster.local:8080
  tenant: billyronks
  namespace: extract-scheduling
  producers:
    - topic: persistent://billyronks/extract-scheduling/command
    - topic: persistent://billyronks/extract-scheduling/event
  consumers:
    - topic: persistent://billyronks/extract-scheduling/audit
      subscription: extract-scheduling-svc-sub
